// packages/web/infrastructure/vuejs/src/views/Cities.vue
<template>
  <section>
    <h1 class="title">Offices</h1>

    <div class="panel">
      <router-link class="panel-block p-4"
                   v-for="city in vm.cities"
                   :to="'/city/' + city.name"
                   :key="city.name"
                   role="link">
        <h2 class="subtitle">{{ city.name }}</h2>
      </router-link>
    </div>
  </section>
</template>

<script lang="ts">
import { defineComponent, inject, onMounted, ref } from 'vue'
import { CITIES_CONTROLLER_FACTORY } from '@/DependencyInjection'

export default defineComponent({
  name: 'Cities',
  components: {},
  setup() {
    const controller = inject(CITIES_CONTROLLER_FACTORY)!.build()
    const vm = ref(controller.presenter.vm)

    onMounted(() => {
      controller.presenter.subscribeVM(updatedVm => {
        vm.value = { ...updatedVm }
      })
      controller.fetchCities()
    })

    return {
      vm
    }
  }
})
</script>

// packages/web/infrastructure/react/src/modules/Cities.tsx
import React, { Fragment, useEffect, useState } from 'react'
import { City } from '@grenoble-hands-on/domain'
import { Link } from 'react-router-dom'
import { CitiesControllerFactory } from '@grenoble-hands-on/web-adapters'

export function Cities(props: { citiesControllerFactory: CitiesControllerFactory }) {
    const controller = props.citiesControllerFactory.build()

    const [vm, setVm] = useState(controller.presenter.vm)

    useEffect(() => {
        controller.fetchCities()
        controller.presenter.subscribeVM((state) => {
            setVm({ ...state })
        })
    }, [])

    return (
        <Fragment>
            <h1 className="title">Offices</h1>
            <div className="panel">
                {vm.cities?.map((city: City) => (
                    <Link className="panel-block p-4" to={'/city/' + city.name} key={city.name}>
                        <h2 className="subtitle">{city.name}</h2>
                    </Link>
                ))}
            </div>
        </Fragment>
    )
}
