// packages/web/infrastructure/angular/src/app/shared/components/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core'

@Component({
  selector: 'app-navbar',
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.scss']
})
export class NavbarComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<nav class="navbar is-primary" role="navigation" aria-label="main navigation">
  <div class="container">
    <a class="navbar-brand" [routerLink]="'/'">
      <h1 class="title navbar-item">
        Zenika Cities weather
      </h1>
    </a>
    <div class="navbar-menu">
      <h2 class="navbar-item has-text-white">
        The best weather app in Angular
      </h2>
      <a class="navbar-item has-text-white" [routerLink]="['/', 'create']">
        Add city
      </a>
    </div>
  </div>
</nav>

// packages/web/infrastructure/react/src/components/Navbar.tsx
import { Link } from 'react-router-dom'
import { FunctionComponent } from 'react'

export const Navbar: FunctionComponent = () => {
    return <nav className="navbar is-primary" role="navigation" aria-label="main navigation">
        <div className="container">
            <Link className="navbar-brand" to={'/'}>
                <h1 className="title navbar-item">
                    Zenika Cities weather
                </h1>
            </Link>
            <div className="navbar-menu">
                <h2 className="navbar-item has-text-white">
                    The best weather app in Angular
                </h2>
                <Link className="navbar-item has-text-white" to={'/create'}>
                    Add city
                </Link>
            </div>
        </div>
    </nav>
}
