// packages/infrastructure/vuejs/src/components/Navbar.vue
<template>
  <nav class="navbar is-primary" role="navigation" aria-label="main navigation">
    <div class="container">
      <router-link class="navbar-brand" to="/">
        <h1 class="title navbar-item">
          Zenika Cities weather
        </h1>
      </router-link>
      <div class="navbar-menu">
        <h2 class="navbar-item has-text-white">
          The best weather app in Vuejs
        </h2>
        <router-link class="navbar-item has-text-white" to="/create">
          Add city
        </router-link>
      </div>
    </div>
  </nav>
</template>

// packages/web/infrastructure/react/src/components/Navbar.tsx
import { Link } from 'react-router-dom'
import { FunctionComponent } from 'react'

export const Navbar: FunctionComponent = () => {
    return <nav className="navbar is-primary" role="navigation" aria-label="main navigation">
        <div className="container">
            <Link className="navbar-brand" to={'/'}>
                <h1 className="title navbar-item">
                    Zenika Cities weather
                </h1>
            </Link>
            <div className="navbar-menu">
                <h2 className="navbar-item has-text-white">
                    The best weather app in Angular
                </h2>
                <Link className="navbar-item has-text-white" to={'/create'}>
                    Add city
                </Link>
            </div>
        </div>
    </nav>
}
