// packages/infrastructure/angular/src/app/shared/components/navbar/navbar.component.ts
import { Component, OnInit } from '@angular/core'
import { NavbarController, NavbarControllerFactory, NavbarPresenterVM } from '@grenoble-hands-on/web-adapters'
import { Observable } from 'rxjs'

@Component({
    selector: 'app-navbar',
    templateUrl: './navbar.component.html',
    styleUrls: ['./navbar.component.scss'],
    providers: [
        {
            provide: NavbarController,
            useFactory: (presenterFactory: NavbarControllerFactory) => presenterFactory.build(),
            deps: [NavbarControllerFactory]
        }
    ]
})
export class NavbarComponent implements OnInit {
    vm$: Observable<NavbarPresenterVM> = new Observable<NavbarPresenterVM>(subscriber =>
        this.controller.subscribeVM(vm => subscriber.next(vm))
    )

    constructor(private readonly controller: NavbarController) {
    }

    ngOnInit(): void {
        this.controller.fetchBookmarkCityWeather()
    }

}

<nav class="navbar is-primary" role="navigation" aria-label="main navigation" *ngIf="vm$ | async as vm">
    <div class="container">
        <a class="navbar-brand" [routerLink]="'/'">
            <h1 class="title navbar-item">
                Zenika Cities weather
            </h1>
        </a>
        <div class="navbar-menu">
            <h2 class="navbar-item has-text-white">
                The best weather app in Angular
            </h2>
            <a class="navbar-item has-text-white" [routerLink]="['/', 'create']">
                Add city
            </a>
            <div class="navbar-end">
                <div *ngIf="vm.bookmarkCityWeather"
                     class="navbar-item has-text-white">
                    <app-weather-widget [weather]="vm.bookmarkCityWeather"></app-weather-widget>
                </div>
                <div *ngIf="vm.bookmarkCityWeatherMessage" class="navbar-item has-text-white" aria-label="weather not display">{{vm.bookmarkCityWeatherMessage}}</div>
            </div>
        </div>
    </div>
</nav>

// packages/infrastructure/react/src/components/Navbar.tsx
import { Link } from 'react-router-dom'
import { Component } from 'react'
import { NavbarController, NavbarControllerFactory, NavbarPresenterVM } from '@grenoble-hands-on/web-adapters'
import { WeatherWidget } from './WeatherWidget'


export type NavbarProps = {
    navbarControllerFactory: NavbarControllerFactory
}

export class Navbar extends Component<NavbarProps, NavbarPresenterVM> {

    private controller: NavbarController

    constructor(public props: NavbarProps) {
        super(props)
        this.controller = this.props.navbarControllerFactory.build()
        this.state = this.controller.vm
    }

    componentDidMount() {
        this.controller.subscribeVM((vm: NavbarPresenterVM) => {
            console.log(vm)
            this.setState({ ...vm })
        })
        this.controller.fetchBookmarkCityWeather()
    }

    render() {
        const vm = this.state

        return (
            <nav className="navbar is-primary" role="navigation" aria-label="main navigation">
                <div className="container">
                    <Link className="navbar-brand" to={'/'}>
                        <h1 className="title navbar-item">
                            Zenika Cities weather
                        </h1>
                    </Link>
                    <div className="navbar-menu">
                        <h2 className="navbar-item has-text-white">
                            The best weather app in React
                        </h2>
                        <Link className="navbar-item has-text-white" to={'/create'}>
                            Add city
                        </Link>
                        <div className="navbar-end">
                            {vm.bookmarkCityWeather &&
                            <div className="navbar-item has-text-white">
                              <WeatherWidget weather={vm.bookmarkCityWeather!}/>
                            </div>
                            }
                            {vm.bookmarkCityWeatherMessage &&
                            <div className="navbar-item has-text-white"
                                 aria-label="weather not display">{vm.bookmarkCityWeatherMessage}
                            </div>
                            }
                        </div>
                    </div>
                </div>
            </nav>
        )
    }
}
