// packages/infrastructure/angular/src/app/shared/components/weather-widget/weather-widget.component.ts
import { Component, Input, OnInit } from '@angular/core'
import { DailyWeather } from '@grenoble-hands-on/domain'

@Component({
    selector: 'app-weather-widget',
    templateUrl: './weather-widget.component.html',
    styleUrls: ['./weather-widget.component.scss']
})
export class WeatherWidgetComponent implements OnInit {

    @Input() weather!: DailyWeather

    constructor() {
    }

    ngOnInit(): void {
    }

}

<img [src]="'https://ssl.gstatic.com/onebox/weather/32/'+weather?.weather+'.png'"
     [alt]="weather?.weather">
<div>{{weather.temperatureMax}} {{weather.unite}}° / {{weather.temperatureMin}} {{weather.unite}}°</div>

// packages/infrastructure/react/src/components/WeatherWidget.tsx
import { DailyWeather } from '@grenoble-hands-on/domain'
import React, { Fragment } from 'react'

export function WeatherWidget(props: { weather: DailyWeather }) {
    return <Fragment>
        <img src={'https://ssl.gstatic.com/onebox/weather/32/' + props.weather.weather + '.png'} alt={props.weather?.weather}/>
        <div>{props.weather.temperatureMax} {props.weather.unite}° / {props.weather.temperatureMin} {props.weather.unite}°</div>
    </Fragment>
}
