// packages/infrastructure/angular/src/app/modules/cities/cities.component.ts
import { Component, OnInit } from '@angular/core'
import { CitiesController, CitiesControllerFactory, CitiesPresenterVM } from '@grenoble-hands-on/web-adapters'
import { Observable } from 'rxjs'

@Component({
    selector: 'app-cities',
    templateUrl: './cities.component.html',
    styleUrls: ['./cities.component.scss'],
    providers: [
        {
            provide: CitiesController,
            useFactory: (presenterFactory: CitiesControllerFactory) => presenterFactory.build(),
            deps: [CitiesControllerFactory]
        }
    ]
})
export class CitiesComponent implements OnInit {
    vm$: Observable<CitiesPresenterVM> = new Observable<CitiesPresenterVM>(subscriber =>
        this.controller.subscribeVM(vm => subscriber.next(vm))
    )

    constructor(private controller: CitiesController) {
    }

    ngOnInit(): void {
        this.controller.fetchCities()
    }

    bookmarkCity($event: MouseEvent, city: string) {
        $event.stopImmediatePropagation()
        $event.preventDefault()
        this.controller.bookmarkCity(city)
    }

}

<section *ngIf="vm$ | async as vm">
    <h1 class="title">Offices</h1>

    <div class="panel">
        <a class="panel-block p-4 is-justify-content-space-between is-align-content-center" [routerLink]="['/city', city.name]" *ngFor="let city of vm.cities">
            <h2 class="subtitle m-0">{{ city.name }}</h2>
            <button class="button" (click)="bookmarkCity($event, city.name)">
                <span class="icon is-small" *ngIf="vm.favoriteCityId === city.name">✅</span>
                <span class="icon is-small" *ngIf="vm.favoriteCityId !== city.name">⭐️</span>
            </button>
        </a>
    </div>
</section>

// packages/infrastructure/react/src/modules/Cities.tsx
import React, { Component, Fragment } from 'react'
import { City } from '@grenoble-hands-on/domain'
import { Link } from 'react-router-dom'
import { CitiesController, CitiesControllerFactory, CitiesPresenterVM } from '@grenoble-hands-on/web-adapters'

export class Cities extends Component<{ citiesControllerFactory: CitiesControllerFactory }, CitiesPresenterVM> {

    private controller: CitiesController

    constructor(public props: { citiesControllerFactory: CitiesControllerFactory }) {
        super(props)
        this.controller = this.props.citiesControllerFactory.build()
        this.state = this.controller.vm
    }

    componentDidMount() {
        this.controller.fetchCities()
        this.controller.subscribeVM((vm: CitiesPresenterVM) => {
            this.setState({ ...vm })
        })
    }

    render() {
        const vm = this.state
        return (
            <Fragment>
                <h1 className="title">Offices</h1>
                <div className="panel">
                    {vm.cities?.map((city: City) => (
                        <Link className="panel-block p-4 is-justify-content-space-between is-align-content-center" to={'/city/' + city.name}
                              key={city.name}>
                            <h2 className="subtitle">{city.name}</h2>
                            <button className={`button ${vm.favoriteCityId === city.name ? 'is-success' : ''}`} onClick={($event) => {
                                $event.stopPropagation()
                                $event.preventDefault()
                                this.controller.bookmarkCity(city.name)
                            }}>
                                <span className="icon is-small">⭐️</span>
                            </button>
                        </Link>
                    ))}
                </div>
            </Fragment>
        )
    }
}
