// packages/web/infrastructure/react/src/modules/AddCity.tsx
import { AddCityController, AddCityControllerFactory, AddCityPresenterVM } from '@grenoble-hands-on/web-adapters'
import { Component } from 'react'

export type AddCityProps = {
    addCityControllerFactory: AddCityControllerFactory
}

export class AddCity extends Component<AddCityProps, AddCityPresenterVM> {

    private controller: AddCityController

    constructor(public props: AddCityProps) {
        super(props)
        this.controller = this.props.addCityControllerFactory.build()
        this.state = this.controller.presenter.vm
    }

    componentDidMount() {
        this.controller.presenter.subscribeVM((vm: AddCityPresenterVM) => {
            this.setState({ ...vm })
        })
    }

    render() {
        const vm = this.state

        return (
            <section>
                <h1 className="title">Create city</h1>

                <div className="card">
                    <form className="card-content" role="form" onSubmit={() => this.controller.create()}>
                        <div className="field city-name">
                            <label htmlFor="city-name-input" className="label">Name</label>
                            <div className="control">
                                <input id="city-name-input" className="input" type="text"
                                       onChange={($event) => this.controller.validateCityName($event.target.value)}
                                       placeholder="City name"/>
                            </div>
                            {vm.cityNameError ?
                                <p className="help is-danger" role="alert" aria-label="city name error">{vm.cityNameError}</p> : null}
                        </div>
                        <div className="field latitude">
                            <label htmlFor="latitude-input" className="label">Latitude</label>
                            <div className="control">
                                <input id="latitude-input" className="input" type="text"
                                       onChange={($event) => this.controller.validateLatitude($event.target.value)}
                                       placeholder="Latitude"/>
                            </div>
                            {vm.latitudeError ?
                                <p className="help is-danger" role="alert" aria-label="latitude error">{vm.latitudeError}</p> : null}
                        </div>
                        <div className="field longitude">
                            <label htmlFor="longitude-input" className="label">Longitude</label>
                            <div className="control">
                                <input id="longitude-input" className="input" type="text"
                                       onChange={($event) => this.controller.validateLongitude($event.target.value)}
                                       placeholder="Longitude"/>
                            </div>
                            {vm.longitudeError ?
                                <p className="help is-danger" role="alert" aria-label="longitude error">{vm.longitudeError}</p> : null}
                        </div>
                        <div className="control">
                            <button type="submit" className="button is-primary" disabled={!vm.canCreateCity}>Create</button>
                        </div>
                    </form>
                </div>
            </section>
        )
    }
}

// packages/web/infrastructure/angular/src/app/modules/add-city/add-city.component.ts
import { Component } from '@angular/core'
import { AddCityController, AddCityControllerFactory, AddCityPresenterVM } from '@grenoble-hands-on/web-adapters'
import { Observable } from 'rxjs'

@Component({
    selector: 'app-add-city',
    templateUrl: './add-city.component.html',
    styleUrls: ['./add-city.component.scss'],
    providers: [
        {
            provide: AddCityController,
            useFactory: (presenterFactory: AddCityControllerFactory) => presenterFactory.build(),
            deps: [AddCityControllerFactory]
        }
    ]
})
export class AddCityComponent {
    vm$: Observable<AddCityPresenterVM> = new Observable<AddCityPresenterVM>(subscriber =>
        this.controller.presenter.subscribeVM(vm => subscriber.next(vm))
    )

    constructor(private controller: AddCityController) {
    }

    createCity($event: Event) {
        this.controller.create()
        $event.preventDefault()
    }

    validateCityName($event: Event) {
        this.controller.validateCityName(($event.target as HTMLInputElement).value)
    }

    validateLatitude($event: Event) {
        this.controller.validateLatitude(($event.target as HTMLInputElement).value)
    }

    validateLongitude($event: Event) {
        this.controller.validateLongitude(($event.target as HTMLInputElement).value)
    }
}

<h1 class="title">Create city</h1>

<div class="card" *ngIf="vm$ | async as vm">
  <form class="card-content" (submit)="createCity($event)" role="form">
    <div class="field city-name">
      <label for="city-name-input" class="label">Name</label>
      <div class="control">
        <input id="city-name-input" class="input" type="text" (change)="validateCityName($event)" placeholder="City name">
      </div>
      <p class="help is-danger" *ngIf="vm.cityNameError" aria-label="city name error">{{vm.cityNameError}}</p>
    </div>
    <div class="field latitude">
      <label for="latitude-input"  class="label">Latitude</label>
      <div class="control">
        <input id="latitude-input" class="input" type="text" (change)="validateLatitude($event)" placeholder="Latitude">
      </div>
      <p class="help is-danger" *ngIf="vm.latitudeError" aria-label="latitude error">{{vm.latitudeError}}</p>
    </div>
    <div class="field longitude">
      <label for="longitude-input" class="label">Longitude</label>
      <div class="control">
        <input id="longitude-input" class="input" type="text" (change)="validateLongitude($event)" placeholder="Longitude">
      </div>
      <p class="help is-danger" *ngIf="vm.longitudeError" aria-label="longitude error">{{vm.longitudeError}}</p>
    </div>
    <div class="control">
      <button type="submit" class="button is-primary" [disabled]="!vm.canCreateCity">Create</button>
    </div>
  </form>
</div>
