// packages/web/infrastructure/react/src/components/Footer.tsx
export function Footer() {
    return <footer className="footer">
        <p className="content has-text-centered">
            Developed by
            <a href="https://github.com/P0ppoff" rel="nofollow">Jules Hablot</a> with
            <a href="https://github.com/chocho01" rel="nofollow">Martin Choraine</a> with
            <a href="https://github.com/thuchede" rel="nofollow">Thomas Huchede</a> with
            <a href="https://github.com/hadrien-thomas-zenika" rel="nofollow">Hadrien Thomas</a> with
            <a href="http://www.7timer.info/index.php" rel="nofollow">7Timer!</a> for
            <a href="https://zenika.com/" rel="nofollow">Zenika</a> with ❤️
        </p>
    </footer>
}

// packages/infrastructure/angular/src/app/shared/components/footer/footer.component.ts
import { Component, OnInit } from '@angular/core'

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrls: ['./footer.component.scss']
})
export class FooterComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}

<footer class="footer">
  <p class="content has-text-centered">
    Developed by
    <a href="https://github.com/P0ppoff" rel="nofollow">Jules Hablot</a> with
    <a href="https://github.com/chocho01" rel="nofollow">Martin Choraine</a> with
    <a href="https://github.com/thuchede" rel="nofollow">Thomas Huchede</a> with
    <a href="https://github.com/hadrien-thomas-zenika" rel="nofollow">Hadrien Thomas</a> with
    <a href="http://www.7timer.info/index.php" rel="nofollow">7Timer!</a> for
    <a href="https://zenika.com/" rel="nofollow">Zenika</a> with ❤️
  </p>
</footer>
