// packages/web/infrastructure/react/src/modules/AddCity.tsx
import { AddCityController, AddCityControllerFactory, AddCityPresenterVM } from '@grenoble-hands-on/web-adapters'
import { Component } from 'react'

export type AddCityProps = {
    addCityControllerFactory: AddCityControllerFactory
}

export class AddCity extends Component<AddCityProps, AddCityPresenterVM> {

    private controller: AddCityController

    constructor(public props: AddCityProps) {
        super(props)
        this.controller = this.props.addCityControllerFactory.build()
        this.state = this.controller.presenter.vm
    }

    componentDidMount() {
        this.controller.presenter.subscribeVM((vm: AddCityPresenterVM) => {
            this.setState({ ...vm })
        })
    }

    render() {
        const vm = this.state

        return (
            <section>
                <h1 className="title">Create city</h1>

                <div className="card">
                    <form className="card-content" role="form" onSubmit={() => this.controller.create()}>
                        <div className="field city-name">
                            <label htmlFor="city-name-input" className="label">Name</label>
                            <div className="control">
                                <input id="city-name-input" className="input" type="text"
                                       onChange={($event) => this.controller.validateCityName($event.target.value)}
                                       placeholder="City name"/>
                            </div>
                            {vm.cityNameError ?
                                <p className="help is-danger" role="alert" aria-label="city name error">{vm.cityNameError}</p> : null}
                        </div>
                        <div className="field latitude">
                            <label htmlFor="latitude-input" className="label">Latitude</label>
                            <div className="control">
                                <input id="latitude-input" className="input" type="text"
                                       onChange={($event) => this.controller.validateLatitude($event.target.value)}
                                       placeholder="Latitude"/>
                            </div>
                            {vm.latitudeError ?
                                <p className="help is-danger" role="alert" aria-label="latitude error">{vm.latitudeError}</p> : null}
                        </div>
                        <div className="field longitude">
                            <label htmlFor="longitude-input" className="label">Longitude</label>
                            <div className="control">
                                <input id="longitude-input" className="input" type="text"
                                       onChange={($event) => this.controller.validateLongitude($event.target.value)}
                                       placeholder="Longitude"/>
                            </div>
                            {vm.longitudeError ?
                                <p className="help is-danger" role="alert" aria-label="longitude error">{vm.longitudeError}</p> : null}
                        </div>
                        <div className="control">
                            <button type="submit" className="button is-primary" disabled={!vm.canCreateCity}>Create</button>
                        </div>
                    </form>
                </div>
            </section>
        )
    }
}

// packages/web/infrastructure/vuejs/src/views/AddCity.vue
<template>
  <h1 class="title">Create city</h1>

  <div class="card">
    <form class="card-content" role="form" @submit.prevent="createCity()">
      <div class="field city-name">
        <label for="city-name-input" class="label">Name</label>
        <div class="control">
          <input id="city-name-input" class="input" type="text" @input="validateCityName($event.target.value)"
                 placeholder="City name">
        </div>
        <p class="help is-danger" v-if="vm.cityNameError" aria-label="city name error">{{ vm.cityNameError }}</p>
      </div>
      <div class="field latitude">
        <label for="latitude-input" class="label">Latitude</label>
        <div class="control">
          <input id="latitude-input" class="input" type="text" @input="validateLatitude($event.target.value)"
                 placeholder="Latitude">
        </div>
        <p class="help is-danger" v-if="vm.latitudeError" aria-label="latitude error">{{ vm.latitudeError }}</p>
      </div>
      <div class="field longitude">
        <label for="longitude-input" class="label">Longitude</label>
        <div class="control">
          <input id="longitude-input" class="input" type="text" @input="validateLongitude($event.target.value)"
                 placeholder="Longitude">
        </div>
        <p class="help is-danger" v-if="vm.longitudeError" aria-label="longitude error">{{ vm.longitudeError }}</p>
      </div>
      <div class="control">
        <button type="submit" class="button is-primary" :disabled="!vm.canCreateCity">Create</button>
      </div>
    </form>
  </div>
</template>

<script lang="ts">
import { defineComponent, inject, onMounted, ref } from 'vue'
import { AddCityController } from '@grenoble-hands-on/web-adapters'
import { ADD_CITY_CONTROLLER_FACTORY } from '@/DependencyInjection'

export default defineComponent({
  name: 'AddCity',
  components: {},
  setup() {
    const controller = inject(ADD_CITY_CONTROLLER_FACTORY)?.build() as AddCityController
    const vm = ref(controller.presenter.vm)

    onMounted(() => {
      controller.presenter.subscribeVM(updatedVm => {
        vm.value = { ...updatedVm }
      })
    })

    return {
      vm,
      validateCityName(input: string) {
        controller.validateCityName(input)
      },
      validateLatitude(input: string) {
        controller.validateLatitude(input)
      },
      validateLongitude(input: string) {
        controller.validateLongitude(input)
      },
      createCity() {
        controller.create()
      },
    }
  }
})
</script>
