// packages/web/infrastructure/react/src/modules/Cities.tsx
import React, { Fragment, useEffect, useState } from 'react'
import { City } from '@grenoble-hands-on/domain'
import { Link } from 'react-router-dom'
import { CitiesPresenterFactory } from '@grenoble-hands-on/web-adapters'

export function Cities(props: { citiesPresenterFactory: CitiesPresenterFactory }) {
    const citiesPresenter = props.citiesPresenterFactory.build()

    const [vm, setVm] = useState(citiesPresenter.vm)

    useEffect(() => {
        citiesPresenter.fetchCities().then()
        citiesPresenter.onVmUpdate((state) => {
            setVm({ ...state })
        })
    }, [])

    return (
        <Fragment>
            <h1 className="title">Offices</h1>
            <div className="panel">
                {vm.cities?.map((city: City) => (
                    <Link className="panel-block p-4" to={'/city/' + city.name} key={city.name}>
                        <h2 className="subtitle">{city.name}</h2>
                    </Link>
                ))}
            </div>
        </Fragment>
    )
}

// packages/web/infrastructure/angular/src/app/modules/cities/cities.component.ts
import {Component, OnInit} from '@angular/core';
import {CitiesPresenter, CitiesPresenterFactory, CitiesPresenterVM} from '@grenoble-hands-on/web-adapters';
import {Observable} from 'rxjs';

@Component({
  selector: 'app-cities',
  templateUrl: './cities.component.html',
  styleUrls: ['./cities.component.scss'],
  providers: [
    {
      provide: CitiesPresenter,
      useFactory: (presenterFactory: CitiesPresenterFactory) => presenterFactory.build(),
      deps: [CitiesPresenterFactory]
    }
  ]
})
export class CitiesComponent implements OnInit {
  vm$: Observable<CitiesPresenterVM> = new Observable<CitiesPresenterVM>(subscriber =>
    this.citiesPresenter.onVmUpdate(vm => subscriber.next(vm))
  );

  constructor(private citiesPresenter: CitiesPresenter) {
  }

  ngOnInit(): void {
    this.citiesPresenter.fetchCities().then();
  }

}

<section *ngIf="vm$ | async as vm">
  <h1 class="title">Offices</h1>

  <div class="panel">
    <a class="panel-block p-4" [routerLink]="['/city', city.name]" *ngFor="let city of vm.cities">
      <h2 class="subtitle">{{ city.name }}</h2>
    </a>
  </div>
</section>
