// packages/web/infrastructure/vuejs/src/App.vue
<template>
  <Navbar></Navbar>

  <section class="section">
    <div class="container">
      <router-view/>
    </div>
  </section>

  <Footer/>
</template>

<script>
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'

export default {
  components: {
    Footer,
    Navbar
  }
}
</script>

<style lang="scss">
@import "~bulma";


.section {
  min-height: 75vh;
}
</style>

// packages/infrastructure/angular/src/app/app.component.ts
import { Component } from '@angular/core'

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: ['./app.component.scss']
})
export class AppComponent {
    title = 'HandsOnCleanArchitectureAngular'
}

<app-navbar></app-navbar>

<section class="section">
  <div class="container">
    <router-outlet></router-outlet>
  </div>
</section>

<app-footer></app-footer>
